// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	refreshTokenFieldNames          = builder.RawFieldNames(&RefreshToken{}, true)
	refreshTokenRows                = strings.Join(refreshTokenFieldNames, ",")
	refreshTokenRowsExpectAutoSet   = strings.Join(stringx.Remove(refreshTokenFieldNames, "id", "create_time", "update_time"), ",")
	refreshTokenRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(refreshTokenFieldNames, "id", "create_time", "update_time"))

	cachePublicRefreshTokenIdPrefix = "cache:public:refreshToken:id:"
)

type (
	refreshTokenModel interface {
		Insert(ctx context.Context, data *RefreshToken) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*RefreshToken, error)
		Update(ctx context.Context, data *RefreshToken) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRefreshTokenModel struct {
		sqlc.CachedConn
		table string
	}

	RefreshToken struct {
		Id        int64        `db:"id"`
		Token     string       `db:"token"`
		UserId    string       `db:"user_id"`
		CreatedAt time.Time    `db:"created_at"`
		ExpiresAt sql.NullTime `db:"expires_at"`
	}
)

func newRefreshTokenModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultRefreshTokenModel {
	return &defaultRefreshTokenModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      `"public"."refresh_token"`,
	}
}

func (m *defaultRefreshTokenModel) Insert(ctx context.Context, data *RefreshToken) (sql.Result, error) {
	publicRefreshTokenIdKey := fmt.Sprintf("%s%v", cachePublicRefreshTokenIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, refreshTokenRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Token, data.UserId, data.CreatedAt, data.ExpiresAt)
	}, publicRefreshTokenIdKey)
	return ret, err
}

func (m *defaultRefreshTokenModel) FindOne(ctx context.Context, id int64) (*RefreshToken, error) {
	publicRefreshTokenIdKey := fmt.Sprintf("%s%v", cachePublicRefreshTokenIdPrefix, id)
	var resp RefreshToken
	err := m.QueryRowCtx(ctx, &resp, publicRefreshTokenIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", refreshTokenRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRefreshTokenModel) Update(ctx context.Context, data *RefreshToken) error {
	publicRefreshTokenIdKey := fmt.Sprintf("%s%v", cachePublicRefreshTokenIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, refreshTokenRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Id, data.Token, data.UserId, data.CreatedAt, data.ExpiresAt)
	}, publicRefreshTokenIdKey)
	return err
}

func (m *defaultRefreshTokenModel) Delete(ctx context.Context, id int64) error {
	publicRefreshTokenIdKey := fmt.Sprintf("%s%v", cachePublicRefreshTokenIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicRefreshTokenIdKey)
	return err
}

func (m *defaultRefreshTokenModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cachePublicRefreshTokenIdPrefix, primary)
}

func (m *defaultRefreshTokenModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", refreshTokenRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultRefreshTokenModel) tableName() string {
	return m.table
}
