// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	Username   string `form:"username"`
	First_name string `form:"first_name"`
	Last_name  string `form:"last_name"`
	Password   string `form:"password"`
	Gender     string `form:"gender"`
	Dob        string `form:"dob"`
}

type RegisterResp struct {
	Id         string `form:"id"`
	Username   string `form:"username"`
	First_name string `form:"first_name"`
	Last_name  string `form:"last_name"`
	Gender     string `form:"gender"`
	Dob        string `form:"dob"`
}
