// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	Username   string `json:"username"`
	First_name string `json:"first_name"`
	Last_name  string `json:"last_name"`
	Password   string `json:"password"`
	Gender     string `json:"gender"`
	Dob        string `json:"dob"`
}

type RegisterResp struct {
	Id         string `json:"id"`
	Username   string `json:"username"`
	First_name string `json:"first_name"`
	Last_name  string `json:"last_name"`
	Gender     string `json:"gender"`
	Dob        string `json:"dob"`
}
