# Zookeeper StatefulSet
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect
  namespace: {{ default .Release.Namespace .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: connect
  replicas: 1
  template:
    metadata:
      labels:
        app: connect
    spec:
      containers:
        - name: connect
          image: asia.gcr.io/cyntra/connect-pg-es
          env: 
            - name: BOOTSTRAP_SERVERS
              value: kafka-service:9092
            - name: GROUP_ID
              value: "1"
            - name: CONFIG_STORAGE_TOPIC
              value: deb_connect_configs
            - name: OFFSET_STORAGE_TOPIC
              value: deb_connect_offsets
            - name: STATUS_STORAGE_TOPIC
              value: deb_source_connect_statuses
            - name: REST_HOST_NAME
              value: "0.0.0.0"
---
# Zookeeper StatefulSet Service
apiVersion: v1
kind: Service
metadata:
  name: connect-lb
spec:
  selector:
    app: connect
  ports:
    - port: 8083
      targetPort: 8083
      name: port8083
    - port: 5005
      targetPort: 5005
      name: port5005