# User Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: {{ default .Release.Namespace .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: asia.gcr.io/cyntra/gateway:latest
          env:
            - name: GATEWAY_PORT
              value: "8888"
            - name: ETCD_HOST
              value: etcd:2379
---
# Zookeeper StatefulSet Service
apiVersion: v1
kind: Service
metadata:
  name: gateway-lb
spec:
  selector:
    app: gateway
  ports:
    - port: 8888
      targetPort: 8888