# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   namespace: {{ default .Release.Namespace .Values.namespace }} 
#   name: kubernetes-dashboard
#   namespace: {{ default .Release.Namespace .Values.namespace }}
# spec:
#   rules:
#   - host: localhost
#     http:
#       paths:
#       - backend:
#           service:
#             name: k
#             port:
#               number: 80
#         path: /
#         pathType: Prefix