# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: {{ default .Release.Namespace .Values.namespace }}
spec:
  serviceName: kafka-service
  selector:
    matchLabels:
      app: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: quay.io/debezium/kafka:1.9
          volumeMounts:
            - name: kafka-disk
              mountPath: /kafka/data
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-lb:2181
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka-service
            - name: KAFKA_PORT
              value: "9092"
            - name: "KUBERNETES_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
      # Volume Claim
  volumeClaimTemplates:
    - metadata:
        name: kafka-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
# PostgreSQL StatefulSet Service
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092