# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
  namespace: {{ default .Release.Namespace .Values.namespace }}
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: quay.io/debezium/postgres:12
          volumeMounts:
            - name: postgresql-db-disk
              mountPath: /data
          env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: PGDATA
              value: /data/pgdata
            - name: POSTGRES_DB
              value: cyntra_prod
      # Volume Claim
  volumeClaimTemplates:
    - metadata:
        name: postgresql-db-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
# PostgreSQL StatefulSet Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-db-lb
spec:
  selector:
    app: postgresql-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-pgbouncer
  namespace: {{ default .Release.Namespace .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres-pgbouncer
  template:
    metadata:
      labels:
        app: postgres-pgbouncer
    spec:
      securityContext:
        fsGroup: 1001
      containers:
        - name: postgres-pgbouncer
          image: edoburu/pgbouncer
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: password
            - name: DB_HOST
              value: postgres-db-lb
            - name: DB_NAME
              value: cyntra_prod
            - name: POOL_MODE
              value: transaction
            - name: DEFAULT_POOL_SIZE
              value: '15'
            - name: MIN_POOL_SIZE
              value: '7'
            - name: RESERVE_POOL_SIZE
              value: '7'
            - name: MAX_CLIENT_CONN
              value: '10000'
            - name: MAX_DB_CONNECTIONS
              value: '30'
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
---
# PostgreSQL pgbouncer Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-pgbouncer-lb
spec:
  selector:
    app: postgres-pgbouncer
  ports:
    - port: 5432
      targetPort: 5432