# Product Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: {{ default .Release.Namespace .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: product-service
  replicas: 1
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: asia.gcr.io/cyntra/product-service:latest
          env:
            - name: PRODUCT_SVC_PORT
              value: "8080"
            - name: ETCD_HOST
              value: etcd:2379
            - name: POSTGRES_URL
              value: postgres://postgres:password@postgres-db-lb:5432/cyntra_prod?sslmode=disable
---
# Zookeeper StatefulSet Service
apiVersion: v1
kind: Service
metadata:
  name: product-service-lb
spec:
  selector:
    app: product-service
  ports:
    - port: 8080
      targetPort: 8080