# User Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: {{ default .Release.Namespace .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: asia.gcr.io/cyntra/user-svc:latest
          env:
            - name: USER_SVC_PORT
              value: "8080"
            - name: JWT_SECRET
              value: "topsecret"
            - name: JWT_EXPIRY_SECONDS
              value: "900"
            - name: JWT_REFRESH_EXPIRY_SECONDS
              value: "604800"
            - name: REDIS_URL
              value: redis://redis:6379/0
            - name: REDIS_HOST
              value: redis:6379
            - name: ETCD_HOST
              value: etcd:2379
            - name: POSTGRES_URL
              value: postgres://postgres:password@postgres-db-lb:5432/cyntra_prod?sslmode=disable


---
# Zookeeper StatefulSet Service
apiVersion: v1
kind: Service
metadata:
  name: user-service-lb
spec:
  selector:
    app: user-service
  ports:
    - port: 8080
      targetPort: 8080