Name: product.rpc
ListenOn: 0.0.0.0:${PRODUCT_SVC_PORT}
Etcd:
  Hosts:
  - ${ETCD_HOST}
  Key: product.rpc
Telemetry:
  Endpoint: http://localhost:14268/api/traces
  Batcher: jaeger
DataSource: ${POSTGRES_URL} 
