# This workflow will build a docker container, publish it to Google Container Registry, and deploy it to GKE when there is a push to the "main" branch.
#
# To configure this workflow:
#
# 1. Ensure that your repository contains the necessary configuration for your Google Kubernetes Engine cluster, including deployment.yml, kustomization.yml, service.yml, etc.
#
# 2. Create and configure a Workload Identity Provider for GitHub (https://github.com/google-github-actions/auth#setting-up-workload-identity-federation)
#
# 3. Change the values for the GAR_LOCATION, GKE_ZONE, GKE_CLUSTER, IMAGE, REPOSITORY and DEPLOYMENT_NAME environment variables (below).
#
# For more support on how to run the workflow, please visit https://github.com/google-github-actions/setup-gcloud/tree/master/example-workflows/gke-kustomize

name: Build and Deploy to GKE

on:
  push:
    branches:
      - "feat/kind"

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: asia-south1 # TODO: update region of the Artifact Registry
  GKE_CLUSTER: cyntra  # TODO: update to cluster name
  GKE_ZONE: asia-south1-a  # TODO: update to cluster zone
  DEPLOYMENT_NAME: user-service # TODO: update to deployment name
  REPOSITORY: user-service # TODO: update to Artifact Registry docker repository
  IMAGE: user-service

jobs:
  deploy:

    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    # env:
    #   IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}
    steps:

    - name: Login
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}

    - name: Configure Docker
      run: gcloud auth configure-docker --quiet

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build . -t asia.gcr.io/$PROJECT_ID/$REPOSITORY

    # - name: Test Docker image
    #   run: docker run $IMAGE_NAME sh -c "go test -v"

    - name: Push Docker image
      run: docker push asia.gcr.io/$PROJECT_ID/$REPOSITORY

    # - name: Deploy Docker image
    #   run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} --image $IMAGE_NAME --region us-central1 --platform managed
          
